package li.cil.oc.common.asm;

import net.minecraft.launchwrapper.LaunchClassLoader;
import org.apache.logging.log4j.LogManager;
import org.apache.logging.log4j.Logger;
import org.objectweb.asm.Type;
import org.objectweb.asm.tree.ClassNode;
import org.objectweb.asm.tree.InnerClassNode;
import org.objectweb.asm.tree.MethodNode;

import java.util.ArrayList;
import java.util.List;

public final class TransformerStripMissingClasses {

  private static final Logger log = LogManager.getLogger("OpenComputers");

  // Strip foreign interfaces from scala generated classes. This is
  // primarily intended to clean up mix-ins / synthetic classes
  // generated by Scala.
  public static void transform(LaunchClassLoader loader, String name, ClassNode classNode) {
    List<String> missingInterfaces = new ArrayList<>();
    for (String interfaceName : classNode.interfaces) {
      if (!ASMHelpers.classExists(loader, interfaceName)) {
        log.trace("Stripping interface {} from class {} because it is missing.", interfaceName, name);
        missingInterfaces.add(interfaceName);
      }
    }
    classNode.interfaces.removeAll(missingInterfaces);

    List<InnerClassNode> missingClasses = new ArrayList<>();
    for (InnerClassNode innerClass : classNode.innerClasses) {
      if (innerClass.outerName != null && !ASMHelpers.classExists(loader, innerClass.outerName)) {
        log.trace("Stripping inner class {} from class {} because its type {} is missing.", innerClass.name, name, innerClass.outerName);
        missingClasses.add(innerClass);
      }
    }
    classNode.innerClasses.removeAll(missingClasses);

    List<MethodNode> incompleteMethods = new ArrayList<>();
    for (MethodNode method : classNode.methods) {
      List<String> missing = missingFromSignature(loader, method.desc);
      if (!missing.isEmpty()) {
        log.trace("Stripping method {} from class {} because missing types in signature: {}",
          method.name, name, String.join(", ", missing));
        incompleteMethods.add(method);
      }
    }
    classNode.methods.removeAll(incompleteMethods);
  }

  private static List<String> missingFromSignature(LaunchClassLoader loader, String methodDesc) {
    List<String> missing = new ArrayList<>();
    Type methodType = Type.getMethodType(methodDesc);

    for (Type arg : methodType.getArgumentTypes()) {
      collectMissingType(loader, arg, missing);
    }
    collectMissingType(loader, methodType.getReturnType(), missing);

    return missing;
  }

  private static void collectMissingType(LaunchClassLoader loader, Type type, List<String> missing) {
    while (type.getSort() == Type.ARRAY) {
      type = type.getElementType();
    }

    if (type.getSort() == Type.OBJECT) {
      String internal = type.getInternalName();
      if (!ASMHelpers.classExists(loader, internal)) {
        missing.add(internal);
      }
    }
  }
}
